server:
  port: 9010
spring:
  application:
    name: csms
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: csms
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false